### ISSUE TITLE
Environment can not be loaded into VIVE headset

### ISSUE THREAD

**Issue by helen9975** [andrejfsantos4/BoxED_Environment#1]
When clicking play in Unity, the preview shows up, however, it is not projected in the headset, and shows the following error. Any ideas why?

![image](https://user-images.githubusercontent.com/50860781/198910967-d6f993c2-9a2e-4c1b-91ff-ed01f3367da5.png)

Here are the steps to reproduce the error:
1. Clone BoxED_Environment
2. Open with Unity Editor Version 2020.3.41f1
3. SteamVR extension is imported
4. Click on play

My system configurations are as follows:
* Ubuntu 20.04
* Nvidia RTX 3080
* 32 GB ram

Please let me know if there is anything that I am missing.

Thanks!

**Comment by andrejfsantos4** [comment]
I made this environment available not to replicate the experiments but mostly to serve as a starting point for other similar experiments. As such, it does not have the components for tracking the headset and the gripper, and for actual grasping. To project on the headset you need to add and configure the XR Origin game object.

I will update this repository's documentation to reflect this.
